import { useEffect,useRef,useState } from "react";
import type { MindMap,MindMapEdge,MindMapNode } from "../../types/entities";
import { addMindMapNode,createMindMap,deleteMindMapNode,getMapGraph,listMindMaps,updateMindMapNode } from "../../features/mind-map/mindMapService";
export function MindMapView(){
 const [maps,setMaps]=useState<MindMap[]>([]),[active,setActive]=useState<string|null>(null),[nodes,setNodes]=useState<MindMapNode[]>([]),[edges,setEdges]=useState<MindMapEdge[]>([]),[selected,setSelected]=useState<string|null>(null); const drag=useRef<{id:string,dx:number,dy:number}|null>(null);
 const reload=async(id=active)=>{setMaps(await listMindMaps());if(id){const g=await getMapGraph(id);setNodes(g.nodes);setEdges(g.edges)}};
 useEffect(()=>{void listMindMaps().then(async m=>{if(!m.length){const x=await createMindMap();m=[x.map]}setMaps(m);setActive(m[0].id);const g=await getMapGraph(m[0].id);setNodes(g.nodes);setEdges(g.edges)})},[]);
 const add=async()=>{if(!active)return;const p=nodes.find(n=>n.id===selected)??nodes.find(n=>n.parentId===null);if(!p)return;await addMindMapNode(active,p.id,"Nhánh mới",p.x+180,p.y+(nodes.length%5-2)*70);await reload()};
 return <div className="h-full flex"><aside className="w-56 border-r p-3 space-y-2" style={{borderColor:"var(--color-border)",background:"var(--color-surface)"}}><button className="w-full rounded p-2" style={{background:"var(--color-accent)",color:"var(--color-bg)"}} onClick={async()=>{const x=await createMindMap();setActive(x.map.id);await reload(x.map.id)}}>＋ Sơ đồ mới</button>{maps.map(m=><button className="w-full text-left p-2 rounded" style={{background:active===m.id?"var(--color-surface-alt)":"transparent"}} onClick={()=>{setActive(m.id);void reload(m.id)}} key={m.id}>{m.title}</button>)}</aside><main className="flex-1 relative overflow-hidden" style={{background:"var(--color-canvas-bg)"}}><div className="absolute z-10 left-3 top-3 flex gap-2"><button onClick={add} className="rounded px-3 py-2" style={{background:"var(--color-accent)",color:"var(--color-bg)"}}>＋ Nhánh</button><button disabled={!selected} onClick={async()=>{if(selected){await deleteMindMapNode(selected);setSelected(null);await reload()}}} className="rounded px-3 py-2" style={{background:"var(--color-surface)"}}>Xóa</button></div><svg className="w-full h-full" onPointerMove={e=>{if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect();const x=e.clientX-r.left-drag.current.dx,y=e.clientY-r.top-drag.current.dy;setNodes(ns=>ns.map(n=>n.id===drag.current?.id?{...n,x,y}:n))}} onPointerUp={()=>{const d=drag.current,n=nodes.find(x=>x.id===d?.id);if(n)void updateMindMapNode(n.id,{x:n.x,y:n.y});drag.current=null}}>{edges.map(e=>{const a=nodes.find(n=>n.id===e.sourceId),b=nodes.find(n=>n.id===e.targetId);return a&&b?<path key={e.id} d={`M${a.x+65},${a.y+22} C${a.x+120},${a.y+22} ${b.x-55},${b.y+22} ${b.x},${b.y+22}`} fill="none" stroke="var(--color-connector)" strokeWidth="2"/>:null})}{nodes.map(n=><g key={n.id} transform={`translate(${n.x} ${n.y})`} onPointerDown={e=>{setSelected(n.id);drag.current={id:n.id,dx:e.nativeEvent.offsetX-n.x,dy:e.nativeEvent.offsetY-n.y};e.currentTarget.setPointerCapture(e.pointerId)}}><rect width="130" height="44" rx="12" fill={selected===n.id?"var(--color-accent)":"var(--color-node)"} stroke="var(--color-border)"/><foreignObject width="130" height="44"><input aria-label="Tên nút" value={n.title} onChange={e=>setNodes(ns=>ns.map(x=>x.id===n.id?{...x,title:e.target.value}:x))} onBlur={e=>void updateMindMapNode(n.id,{title:e.target.value})} className="w-full h-full text-center bg-transparent px-2 outline-none"/></foreignObject></g>)}</svg></main></div>
}
