export type TrigramName = "Càn" | "Khôn" | "Chấn" | "Tốn" | "Khảm" | "Ly" | "Cấn" | "Đoài";
export type TrigramInfo = { name: TrigramName; chinese: string; symbol: string; image: string; element: string; nature: string; };
export const ICHING_TRIGRAMS: Record<TrigramName, TrigramInfo> = {
  "Càn": { name: "Càn", chinese: "乾", symbol: "☰", image: "Trời", element: "Kim", nature: "cương kiện, sáng tạo, chủ động" },
  "Khôn": { name: "Khôn", chinese: "坤", symbol: "☷", image: "Đất", element: "Thổ", nature: "nhu thuận, tiếp nhận, nuôi dưỡng" },
  "Chấn": { name: "Chấn", chinese: "震", symbol: "☳", image: "Sấm", element: "Mộc", nature: "khởi động, chấn động, tiến phát" },
  "Tốn": { name: "Tốn", chinese: "巽", symbol: "☴", image: "Gió", element: "Mộc", nature: "thâm nhập, mềm dẻo, lan truyền" },
  "Khảm": { name: "Khảm", chinese: "坎", symbol: "☵", image: "Nước", element: "Thủy", nature: "hiểm, sâu, thích nghi, lưu động" },
  "Ly": { name: "Ly", chinese: "離", symbol: "☲", image: "Lửa", element: "Hỏa", nature: "sáng, bám, nhận thức, văn minh" },
  "Cấn": { name: "Cấn", chinese: "艮", symbol: "☶", image: "Núi", element: "Thổ", nature: "dừng, giới hạn, tĩnh, tích lũy" },
  "Đoài": { name: "Đoài", chinese: "兌", symbol: "☱", image: "Hồ/Đầm", element: "Kim", nature: "vui, giao tiếp, trao đổi, hòa duyệt" },
};

export type IChingHexagram = { number: number; symbol: string; chinese: string; hanViet: string; code: string; upper: TrigramName; lower: TrigramName; theme: string; meaning: string; whenCast: string; keywords: string[]; };

export const ICHING_SOURCES = [
  { id: "ZHOUYI", title: "Chu Dịch · nguyên văn 64 quẻ", url: "https://zh.wikisource.org/zh-hant/周易" },
  { id: "CTEXT", title: "Book of Changes · Chinese Text Project", url: "https://ctext.org/book-of-changes" },
  { id: "TAIBU", title: "Dữ liệu cấu trúc thượng/hạ quái và mã hào (MIT/open source reference)", url: "https://github.com/hhszzzz/taibu/blob/master/packages/core/src/data/hexagrams.ts" },
  { id: "KWJSON", title: "King Wen sequence cross-check dataset", url: "https://github.com/FENGTING2025/iching-64-hexagrams-json/blob/main/hexagrams.json" },
  { id: "COINS", title: "Phương pháp gieo ba đồng xu · 6/7/8/9", url: "https://en.wikipedia.org/wiki/I_Ching_divination" },
] as const;

export const ICHING_HEXAGRAMS: IChingHexagram[] = [
  { number: 1, symbol: "䷀", chinese: "乾", hanViet: "Thuần Càn", code: "111111", upper: "Càn", lower: "Càn", theme: "Sáng tạo · cương kiện", meaning: "Khí dương thuần, tượng Trời: chủ khởi xướng, sức sáng tạo, tự cường và năng lực dẫn dắt.", whenCast: "Thời thế có lực tiến mạnh. Nên chủ động nhưng giữ chính đạo; quá cứng hoặc tự mãn dễ đi đến cực thịnh rồi suy.", keywords: ["Sáng tạo", "cương kiện"] },
  { number: 2, symbol: "䷁", chinese: "坤", hanViet: "Thuần Khôn", code: "000000", upper: "Khôn", lower: "Khôn", theme: "Tiếp nhận · nhu thuận", meaning: "Khí âm thuần, tượng Đất: chủ nâng đỡ, tiếp nhận, nuôi dưỡng và hoàn thành điều đã được khởi xướng.", whenCast: "Hợp đi theo thế đúng, bền bỉ và làm nền. Không cần tranh dẫn đầu; lấy ổn định, hợp tác và kiên trì làm trọng.", keywords: ["Tiếp nhận", "nhu thuận"] },
  { number: 3, symbol: "䷂", chinese: "屯", hanViet: "Thủy Lôi Truân", code: "100010", upper: "Khảm", lower: "Chấn", theme: "Khởi đầu gian khó", meaning: "Tượng mầm sống mới sinh giữa hiểm trở: có tiềm năng nhưng trật tự chưa hình thành.", whenCast: "Việc mới dễ rối, thiếu người hoặc thiếu quy trình. Nên dựng nền, tìm trợ lực, tiến từng bước thay vì thúc kết quả sớm.", keywords: ["Khởi đầu gian khó"] },
  { number: 4, symbol: "䷃", chinese: "蒙", hanViet: "Sơn Thủy Mông", code: "010001", upper: "Cấn", lower: "Khảm", theme: "Mông muội · khai học", meaning: "Tượng người chưa biết đang học cách phân biệt đúng sai; nhấn mạnh giáo dục, hỏi đúng và kỷ luật học tập.", whenCast: "Ra quẻ này nên học, hỏi người có kinh nghiệm và tránh hỏi đi hỏi lại chỉ để tìm câu trả lời mình thích.", keywords: ["Mông muội", "khai học"] },
  { number: 5, symbol: "䷄", chinese: "需", hanViet: "Thủy Thiên Nhu", code: "111010", upper: "Khảm", lower: "Càn", theme: "Chờ thời · dưỡng lực", meaning: "Có năng lực tiến nhưng trước mặt còn hiểm; chờ đúng thời điểm không phải thụ động mà là chuẩn bị.", whenCast: "Chưa nên cưỡng tiến. Hãy củng cố nguồn lực, thông tin và niềm tin; thời cơ chín thì hành động dứt khoát.", keywords: ["Chờ thời", "dưỡng lực"] },
  { number: 6, symbol: "䷅", chinese: "訟", hanViet: "Thiên Thủy Tụng", code: "010111", upper: "Càn", lower: "Khảm", theme: "Tranh tụng · bất đồng", meaning: "Hai phía đi ngược nhau, dễ thành tranh chấp, lý lẽ hoặc kiện tụng.", whenCast: "Nên tìm điểm dừng và người trung gian có uy tín. Càng cố thắng đến cùng càng dễ hao tổn.", keywords: ["Tranh tụng", "bất đồng"] },
  { number: 7, symbol: "䷆", chinese: "師", hanViet: "Địa Thủy Sư", code: "010000", upper: "Khôn", lower: "Khảm", theme: "Tổ chức · kỷ luật", meaning: "Tượng đội ngũ có kỷ luật, cần người chỉ huy chính đáng và mục tiêu rõ.", whenCast: "Muốn thành phải thống nhất nguyên tắc, phân vai và trách nhiệm. Tránh dùng sức mạnh tùy tiện hoặc lãnh đạo thiếu chính danh.", keywords: ["Tổ chức", "kỷ luật"] },
  { number: 8, symbol: "䷇", chinese: "比", hanViet: "Thủy Địa Tỷ", code: "000010", upper: "Khảm", lower: "Khôn", theme: "Gần gũi · liên kết", meaning: "Chủ kết minh, nương tựa và xây cộng đồng dựa trên lòng tin.", whenCast: "Hợp tìm đồng minh và củng cố quan hệ. Nhưng cần chọn đúng người, đúng nhóm; đến quá muộn hoặc kết giao vì lợi ngắn hạn dễ bất lợi.", keywords: ["Gần gũi", "liên kết"] },
  { number: 9, symbol: "䷈", chinese: "小畜", hanViet: "Phong Thiên Tiểu Súc", code: "111011", upper: "Tốn", lower: "Càn", theme: "Tích nhỏ · kiềm lực", meaning: "Sức mạnh được gió mềm giữ lại: tích lũy nhỏ, chỉnh sửa tiểu tiết trước bước lớn.", whenCast: "Chưa phải lúc bứt phá. Gom nguồn lực, sửa chi tiết, tạo thói quen tốt; tiến ít nhưng đều.", keywords: ["Tích nhỏ", "kiềm lực"] },
  { number: 10, symbol: "䷉", chinese: "履", hanViet: "Thiên Trạch Lý", code: "110111", upper: "Càn", lower: "Đoài", theme: "Bước đi đúng lễ", meaning: "Tượng bước gần chỗ nguy nhưng giữ đúng phép thì qua; trọng thái độ và giới hạn.", whenCast: "Có thể tiến nhưng phải cẩn trọng, đúng vai, đúng quy trình. Đừng coi thường rủi ro chỉ vì hiện tại đang thuận.", keywords: ["Bước đi đúng lễ"] },
  { number: 11, symbol: "䷊", chinese: "泰", hanViet: "Địa Thiên Thái", code: "111000", upper: "Khôn", lower: "Càn", theme: "Hanh thông · giao hòa", meaning: "Trời đất giao nhau, trên dưới thông; tượng thời kỳ hanh thông và phối hợp tốt.", whenCast: "Thuận để phát triển, kết nối và mở rộng. Đồng thời phải chuẩn bị lúc thịnh chuyển suy, tránh tiêu xài hết lợi thế.", keywords: ["Hanh thông", "giao hòa"] },
  { number: 12, symbol: "䷋", chinese: "否", hanViet: "Thiên Địa Bĩ", code: "000111", upper: "Càn", lower: "Khôn", theme: "Bế tắc · cách biệt", meaning: "Trời đất không giao, trên dưới xa nhau; tượng hệ thống tắc nghẽn hoặc giá trị không tương hợp.", whenCast: "Không nên cố chen vào môi trường sai. Giữ phẩm chất, thu gọn việc, chờ chu kỳ đổi thay và tránh đánh đổi nguyên tắc để cầu lợi.", keywords: ["Bế tắc", "cách biệt"] },
  { number: 13, symbol: "䷌", chinese: "同人", hanViet: "Thiên Hỏa Đồng Nhân", code: "101111", upper: "Càn", lower: "Ly", theme: "Đồng lòng · cộng tác", meaning: "Lửa dưới trời sáng rõ: con người cùng mục tiêu, minh bạch và hợp tác rộng.", whenCast: "Hợp làm việc nhóm, xây liên minh công khai. Thành công đến từ mục tiêu chung hơn là phe cánh riêng tư.", keywords: ["Đồng lòng", "cộng tác"] },
  { number: 14, symbol: "䷍", chinese: "大有", hanViet: "Hỏa Thiên Đại Hữu", code: "111101", upper: "Ly", lower: "Càn", theme: "Sở hữu lớn · thịnh vượng", meaning: "Tượng có nhiều nguồn lực, vị thế hoặc thành quả; càng nhiều càng cần quản trị đúng.", whenCast: "Có cơ hội lớn. Nên dùng nguồn lực có trách nhiệm, chia lợi ích hợp lý và giữ khiêm để bền.", keywords: ["Sở hữu lớn", "thịnh vượng"] },
  { number: 15, symbol: "䷎", chinese: "謙", hanViet: "Địa Sơn Khiêm", code: "001000", upper: "Khôn", lower: "Cấn", theme: "Khiêm nhường · cân bằng", meaning: "Núi cao nằm trong đất: có thực lực nhưng không phô trương.", whenCast: "Rất hợp giảm cái tôi, làm chắc hơn nói. Khiêm không phải tự hạ thấp mà là đặt mình đúng vị trí.", keywords: ["Khiêm nhường", "cân bằng"] },
  { number: 16, symbol: "䷏", chinese: "豫", hanViet: "Lôi Địa Dự", code: "000100", upper: "Chấn", lower: "Khôn", theme: "Hứng khởi · chuẩn bị", meaning: "Sấm nổi trên đất, khí thế được khơi dậy; có thể động viên tập thể.", whenCast: "Có động lực tốt nhưng phải biến hứng khởi thành kế hoạch. Tránh vui quá sớm hoặc hành động chỉ theo cảm xúc.", keywords: ["Hứng khởi", "chuẩn bị"] },
  { number: 17, symbol: "䷐", chinese: "隨", hanViet: "Trạch Lôi Tùy", code: "100110", upper: "Đoài", lower: "Chấn", theme: "Tùy thời · theo đúng", meaning: "Biết đi theo điều đáng theo và thích nghi với nhịp của hoàn cảnh.", whenCast: "Nên linh hoạt, học từ người/việc đang dẫn đường. Theo nhưng không mù quáng; giữ tiêu chuẩn để biết lúc nào cần đổi hướng.", keywords: ["Tùy thời", "theo đúng"] },
  { number: 18, symbol: "䷑", chinese: "蠱", hanViet: "Sơn Phong Cổ", code: "011001", upper: "Cấn", lower: "Tốn", theme: "Sửa hỏng · chỉnh đốn", meaning: "Chủ xử lý cái đã mục, sai lệch tích lâu hoặc di sản có vấn đề.", whenCast: "Đừng chỉ che triệu chứng. Tìm nguyên nhân gốc, sửa quy trình cũ và dành thời gian kiểm tra trước lẫn sau thay đổi.", keywords: ["Sửa hỏng", "chỉnh đốn"] },
  { number: 19, symbol: "䷒", chinese: "臨", hanViet: "Địa Trạch Lâm", code: "110000", upper: "Khôn", lower: "Đoài", theme: "Tiếp cận · lớn dần", meaning: "Tượng cấp trên/nguồn lực đang đến gần; cơ hội phát triển tăng dần.", whenCast: "Thời vận đang mở, hợp tiếp xúc, hướng dẫn và mở rộng. Nhưng phải nghĩ đến lúc chu kỳ tăng trưởng đạt đỉnh.", keywords: ["Tiếp cận", "lớn dần"] },
  { number: 20, symbol: "䷓", chinese: "觀", hanViet: "Phong Địa Quan", code: "000011", upper: "Tốn", lower: "Khôn", theme: "Quan sát · soi xét", meaning: "Chủ đứng cao quan sát toàn cảnh và cũng để người khác quan sát mình.", whenCast: "Nên tạm chậm để nhìn hệ thống, dữ liệu và tác động. Hành vi của người dẫn dắt đang là tấm gương cho người khác.", keywords: ["Quan sát", "soi xét"] },
  { number: 21, symbol: "䷔", chinese: "噬嗑", hanViet: "Hỏa Lôi Phệ Hạp", code: "100101", upper: "Ly", lower: "Chấn", theme: "Cắn xuyên · xử lý chướng ngại", meaning: "Có vật cản giữa hai phần; cần quyết đoán cắt bỏ bằng quy tắc rõ.", whenCast: "Hợp xử lý vấn đề tồn đọng, vi phạm hoặc nút thắt. Cứng phải đi cùng minh bạch và đúng mức.", keywords: ["Cắn xuyên", "xử lý chướng ngại"] },
  { number: 22, symbol: "䷕", chinese: "賁", hanViet: "Sơn Hỏa Bí", code: "101001", upper: "Cấn", lower: "Ly", theme: "Trang sức · văn vẻ", meaning: "Hình thức làm sáng nội dung nhưng không thể thay nội dung.", whenCast: "Hợp chỉnh trình bày, thương hiệu, lễ nghi và chi tiết thẩm mỹ. Việc lớn vẫn phải dựa trên thực chất, đừng lấy đẹp che rỗng.", keywords: ["Trang sức", "văn vẻ"] },
  { number: 23, symbol: "䷖", chinese: "剝", hanViet: "Sơn Địa Bác", code: "000001", upper: "Cấn", lower: "Khôn", theme: "Bóc rụng · suy giảm", meaning: "Các lớp nâng đỡ đang mất dần; cần bảo toàn lõi thay vì cố mở rộng.", whenCast: "Không thuận tiến lớn. Nên cắt chi phí, bảo vệ nền tảng, rời cấu trúc mục nát và chờ mầm mới xuất hiện.", keywords: ["Bóc rụng", "suy giảm"] },
  { number: 24, symbol: "䷗", chinese: "復", hanViet: "Địa Lôi Phục", code: "100000", upper: "Khôn", lower: "Chấn", theme: "Trở lại · phục hồi", meaning: "Một hào dương trở lại: sau suy giảm bắt đầu có mầm hồi phục.", whenCast: "Tín hiệu quay về đúng đường. Bắt đầu nhỏ, đều và cho chu kỳ mới thời gian lớn lên; chưa cần tăng tốc ngay.", keywords: ["Trở lại", "phục hồi"] },
  { number: 25, symbol: "䷘", chinese: "無妄", hanViet: "Thiên Lôi Vô Vọng", code: "100111", upper: "Càn", lower: "Chấn", theme: "Vô vọng · chân thực", meaning: "Chủ hành động tự nhiên, không vọng tưởng, không tính toán lệch chính đạo.", whenCast: "Nên làm điều đúng vì nó đúng, không cưỡng cầu kết quả. Tránh kế hoạch dựa trên giả định hoặc tham vọng thiếu căn cứ.", keywords: ["Vô vọng", "chân thực"] },
  { number: 26, symbol: "䷙", chinese: "大畜", hanViet: "Sơn Thiên Đại Súc", code: "111001", upper: "Cấn", lower: "Càn", theme: "Tích lớn · hàm dưỡng", meaning: "Sức mạnh lớn được giữ và luyện thành năng lực có ích.", whenCast: "Hợp học sâu, tích vốn, rèn kỹ năng và kiểm soát xung lực. Có thể chuẩn bị cho việc lớn nhưng chưa nên tiêu hết lực.", keywords: ["Tích lớn", "hàm dưỡng"] },
  { number: 27, symbol: "䷚", chinese: "頤", hanViet: "Sơn Lôi Di", code: "100001", upper: "Cấn", lower: "Chấn", theme: "Nuôi dưỡng · lời nói", meaning: "Tượng cái miệng: thức ăn, thông tin và lời nói đều là thứ nuôi hoặc làm hại.", whenCast: "Xem lại mình đang nạp gì và nuôi ai/cái gì. Chú ý chất lượng nguồn lực, ngôn từ và thói quen hằng ngày.", keywords: ["Nuôi dưỡng", "lời nói"] },
  { number: 28, symbol: "䷛", chinese: "大過", hanViet: "Trạch Phong Đại Quá", code: "011110", upper: "Đoài", lower: "Tốn", theme: "Quá tải · gánh lớn", meaning: "Cột giữa chịu tải quá mức; tình thế bất thường đòi hành động khác thường.", whenCast: "Có việc lớn cần gánh nhưng cấu trúc hiện tại không bền. Phải gia cố hoặc thay cách làm; trì hoãn dễ khiến hệ thống gãy.", keywords: ["Quá tải", "gánh lớn"] },
  { number: 29, symbol: "䷜", chinese: "坎", hanViet: "Thuần Khảm", code: "010010", upper: "Khảm", lower: "Khảm", theme: "Hiểm sâu · học qua nguy", meaning: "Nước chảy qua hố liên tiếp: hiểm lặp lại nhưng có đường nếu giữ tâm và kỹ năng.", whenCast: "Đang ở chuỗi thử thách. Tập trung quy trình an toàn, học từ lần trước và không liều vì sốt ruột.", keywords: ["Hiểm sâu", "học qua nguy"] },
  { number: 30, symbol: "䷝", chinese: "離", hanViet: "Thuần Ly", code: "101101", upper: "Ly", lower: "Ly", theme: "Sáng rõ · nương tựa", meaning: "Lửa cần vật để bám: trí sáng phải dựa vào điều đúng và mối liên hệ phù hợp.", whenCast: "Hợp làm rõ, truyền thông và tạo nhận thức. Đừng để vẻ sáng khiến mất chỗ dựa thực tế hoặc lệ thuộc sai đối tượng.", keywords: ["Sáng rõ", "nương tựa"] },
  { number: 31, symbol: "䷞", chinese: "咸", hanViet: "Trạch Sơn Hàm", code: "001110", upper: "Đoài", lower: "Cấn", theme: "Cảm ứng · tương tác", meaning: "Chủ ảnh hưởng qua lại, hấp dẫn và sự đáp ứng giữa hai phía.", whenCast: "Quan hệ có sức cảm ứng. Nên chân thành, tinh tế và để tương tác diễn ra tự nhiên hơn là thao túng.", keywords: ["Cảm ứng", "tương tác"] },
  { number: 32, symbol: "䷟", chinese: "恆", hanViet: "Lôi Phong Hằng", code: "011100", upper: "Chấn", lower: "Tốn", theme: "Bền lâu · nhất quán", meaning: "Chuyển động và thâm nhập phối hợp thành nhịp bền.", whenCast: "Việc cần duy trì nguyên tắc dài hạn. Không phải đứng yên; bền là biết đổi cách nhưng giữ mục tiêu và cam kết cốt lõi.", keywords: ["Bền lâu", "nhất quán"] },
  { number: 33, symbol: "䷠", chinese: "遯", hanViet: "Thiên Sơn Độn", code: "001111", upper: "Càn", lower: "Cấn", theme: "Rút lui · bảo toàn", meaning: "Biết lùi đúng lúc để tránh bị cuốn vào thế bất lợi.", whenCast: "Rút lui chiến lược tốt hơn đối đầu trực diện. Giữ lực, giữ danh dự và chọn trận đáng đánh.", keywords: ["Rút lui", "bảo toàn"] },
  { number: 34, symbol: "䷡", chinese: "大壯", hanViet: "Lôi Thiên Đại Tráng", code: "111100", upper: "Chấn", lower: "Càn", theme: "Sức mạnh lớn", meaning: "Dương khí mạnh và đang bốc lên; có lực nhưng cần chính đáng.", whenCast: "Có năng lượng để tiến. Dùng sức đúng luật, không áp người khác; sức mạnh thiếu tự chế dễ phản tác dụng.", keywords: ["Sức mạnh lớn"] },
  { number: 35, symbol: "䷢", chinese: "晉", hanViet: "Hỏa Địa Tấn", code: "000101", upper: "Ly", lower: "Khôn", theme: "Tiến lên · được thấy", meaning: "Ánh sáng lên trên đất: thành quả dần được công nhận.", whenCast: "Hợp tiến chức, ra mắt, trình bày và mở rộng ảnh hưởng. Hãy minh bạch và mang lợi ích cho tập thể để tiến bền.", keywords: ["Tiến lên", "được thấy"] },
  { number: 36, symbol: "䷣", chinese: "明夷", hanViet: "Địa Hỏa Minh Di", code: "101000", upper: "Khôn", lower: "Ly", theme: "Ánh sáng bị che", meaning: "Sáng ở dưới đất: tài năng hoặc chân lý chưa thể phô ra an toàn.", whenCast: "Nên bảo vệ nội lực, kín đáo và tránh đối đầu vô ích. Giữ nguyên tắc bên trong nhưng điều chỉnh cách biểu lộ.", keywords: ["Ánh sáng bị che"] },
  { number: 37, symbol: "䷤", chinese: "家人", hanViet: "Phong Hỏa Gia Nhân", code: "101011", upper: "Tốn", lower: "Ly", theme: "Gia đạo · vai trò", meaning: "Chủ trật tự trong nhóm gần: gia đình, đội nhỏ, hệ thống có vai trò rõ.", whenCast: "Muốn ổn cần ranh giới, trách nhiệm và giao tiếp nhất quán. Sửa từ bên trong trước khi trách bên ngoài.", keywords: ["Gia đạo", "vai trò"] },
  { number: 38, symbol: "䷥", chinese: "睽", hanViet: "Hỏa Trạch Khuê", code: "110101", upper: "Ly", lower: "Đoài", theme: "Đối lập · khác biệt", meaning: "Hai phía cùng sáng nhưng hướng khác; khác biệt không nhất thiết phải thành thù.", whenCast: "Việc lớn khó đồng thuận, nhưng việc nhỏ có thể hợp tác. Tôn trọng khác biệt, xác định phần chung và đừng ép đồng nhất.", keywords: ["Đối lập", "khác biệt"] },
  { number: 39, symbol: "䷦", chinese: "蹇", hanViet: "Thủy Sơn Kiển", code: "001010", upper: "Khảm", lower: "Cấn", theme: "Trở ngại · khó tiến", meaning: "Trước là hiểm, dưới là dừng: đường thẳng bị chặn.", whenCast: "Không nên cố xông. Lùi một bước, tìm đường vòng hoặc người hỗ trợ; sửa điều kiện trước khi tiếp tục.", keywords: ["Trở ngại", "khó tiến"] },
  { number: 40, symbol: "䷧", chinese: "解", hanViet: "Lôi Thủy Giải", code: "010100", upper: "Chấn", lower: "Khảm", theme: "Giải thoát · tháo nút", meaning: "Sấm mưa làm tan căng thẳng; nút thắt có thể được mở.", whenCast: "Hợp kết thúc tranh chấp, đơn giản hóa và xử lý nhanh việc còn lại. Sau khi giải được, trở về trạng thái bình thường, đừng kéo dài drama.", keywords: ["Giải thoát", "tháo nút"] },
  { number: 41, symbol: "䷨", chinese: "損", hanViet: "Sơn Trạch Tổn", code: "110001", upper: "Cấn", lower: "Đoài", theme: "Giảm bớt · hy sinh đúng", meaning: "Bớt phần dưới để bổ phần trên; chủ cắt giảm có mục đích.", whenCast: "Nên bỏ thứ không thiết yếu để giữ cái quan trọng. Giảm đúng chỗ sẽ tạo khoảng trống cho phát triển sau này.", keywords: ["Giảm bớt", "hy sinh đúng"] },
  { number: 42, symbol: "䷩", chinese: "益", hanViet: "Phong Lôi Ích", code: "100011", upper: "Tốn", lower: "Chấn", theme: "Tăng ích · bổ sung", meaning: "Lợi ích được đưa xuống nơi cần, tạo động lực tăng trưởng.", whenCast: "Hợp đầu tư, giúp người, cải tiến và mở rộng. Tăng trưởng bền khi phần được thêm vào phục vụ cả hệ thống chứ không chỉ một cá nhân.", keywords: ["Tăng ích", "bổ sung"] },
  { number: 43, symbol: "䷪", chinese: "夬", hanViet: "Trạch Thiên Quải", code: "111110", upper: "Đoài", lower: "Càn", theme: "Quyết đoán · tuyên bố", meaning: "Một âm ở trên năm dương: vấn đề cuối cùng phải được nói rõ và xử lý.", whenCast: "Đã đến lúc quyết định và công khai nguyên tắc. Kiên quyết nhưng không dùng bạo lực hay trả đũa; chuẩn bị hậu quả của quyết định.", keywords: ["Quyết đoán", "tuyên bố"] },
  { number: 44, symbol: "䷫", chinese: "姤", hanViet: "Thiên Phong Cấu", code: "011111", upper: "Càn", lower: "Tốn", theme: "Gặp gỡ bất ngờ", meaning: "Một yếu tố mới nhỏ nhưng có sức ảnh hưởng lớn xuất hiện.", whenCast: "Cơ hội hoặc cám dỗ đến nhanh. Hãy đánh giá trước khi gắn kết sâu; đừng coi nhẹ thứ nhỏ nhưng có khả năng đổi toàn cục.", keywords: ["Gặp gỡ bất ngờ"] },
  { number: 45, symbol: "䷬", chinese: "萃", hanViet: "Trạch Địa Tụy", code: "000110", upper: "Đoài", lower: "Khôn", theme: "Tụ họp · quy tụ", meaning: "Nhiều người/nguồn lực tập trung về một điểm, cần trung tâm chung.", whenCast: "Hợp tổ chức sự kiện, xây cộng đồng, huy động nguồn lực. Phải có mục tiêu, nghi thức/quy tắc và người giữ trục.", keywords: ["Tụ họp", "quy tụ"] },
  { number: 46, symbol: "䷭", chinese: "升", hanViet: "Địa Phong Thăng", code: "011000", upper: "Khôn", lower: "Tốn", theme: "Thăng tiến · lớn dần", meaning: "Cây mọc trong đất, tiến lên từng tầng từ nền vững.", whenCast: "Tiến chậm nhưng chắc. Hợp học nghề, tích thành tựu, gặp người nâng đỡ và leo từng bậc thay vì nhảy cấp.", keywords: ["Thăng tiến", "lớn dần"] },
  { number: 47, symbol: "䷮", chinese: "困", hanViet: "Trạch Thủy Khốn", code: "010110", upper: "Đoài", lower: "Khảm", theme: "Khốn khó · cạn lực", meaning: "Nước rút khỏi hồ: nguồn lực thiếu, lời nói khó được tin.", whenCast: "Giai đoạn hạn chế. Giảm kỳ vọng, giữ lõi tinh thần và tập trung thứ kiểm soát được; càng phô trương càng hao.", keywords: ["Khốn khó", "cạn lực"] },
  { number: 48, symbol: "䷯", chinese: "井", hanViet: "Thủy Phong Tỉnh", code: "011010", upper: "Khảm", lower: "Tốn", theme: "Giếng · nguồn chung", meaning: "Giếng tượng nguồn lực cộng đồng bền hơn người sử dụng nó.", whenCast: "Hãy sửa hạ tầng, quy trình hoặc nguồn tri thức dùng chung. Có nguồn tốt mà cách lấy nước hỏng thì vẫn không dùng được.", keywords: ["Giếng", "nguồn chung"] },
  { number: 49, symbol: "䷰", chinese: "革", hanViet: "Trạch Hỏa Cách", code: "101110", upper: "Đoài", lower: "Ly", theme: "Cải cách · đổi chế độ", meaning: "Thời cũ không còn phù hợp, cần đổi sau khi lý do đã chín.", whenCast: "Hợp thay đổi lớn khi có chính danh, thời điểm và đồng thuận đủ. Đổi quá sớm là loạn; đổi quá muộn là mục nát.", keywords: ["Cải cách", "đổi chế độ"] },
  { number: 50, symbol: "䷱", chinese: "鼎", hanViet: "Hỏa Phong Đỉnh", code: "011101", upper: "Ly", lower: "Tốn", theme: "Đỉnh · chuyển hóa", meaning: "Cái đỉnh nấu sống thành chín: biến nguyên liệu thành giá trị văn hóa/chất lượng cao hơn.", whenCast: "Hợp nâng cấp tổ chức, đào tạo người và xây chuẩn mới. Sau cách mạng cần thiết chế hóa cái mới để bền.", keywords: ["Đỉnh", "chuyển hóa"] },
  { number: 51, symbol: "䷲", chinese: "震", hanViet: "Thuần Chấn", code: "100100", upper: "Chấn", lower: "Chấn", theme: "Chấn động · thức tỉnh", meaning: "Sấm lặp lại: biến cố bất ngờ làm người ta tỉnh và phản ứng.", whenCast: "Có tin/việc đến nhanh. Giữ bình tĩnh, xử lý theo quy trình và biến cú sốc thành sự tỉnh táo thay vì hoảng loạn.", keywords: ["Chấn động", "thức tỉnh"] },
  { number: 52, symbol: "䷳", chinese: "艮", hanViet: "Thuần Cấn", code: "001001", upper: "Cấn", lower: "Cấn", theme: "Dừng · tĩnh", meaning: "Núi chồng núi: biết dừng thân và tâm đúng lúc.", whenCast: "Nên ngừng hành động không cần thiết, xác lập ranh giới và quan sát. Dừng đúng lúc là năng lực, không phải thất bại.", keywords: ["Dừng", "tĩnh"] },
  { number: 53, symbol: "䷴", chinese: "漸", hanViet: "Phong Sơn Tiệm", code: "001011", upper: "Tốn", lower: "Cấn", theme: "Tiến dần · trưởng thành", meaning: "Cây trên núi lớn chậm mà bền; chủ tiến triển theo trình tự.", whenCast: "Việc có thể thành nếu tôn trọng thứ tự, thời gian và sự trưởng thành. Tránh ép nhanh chuyện cần nền tảng, nhất là quan hệ và nghề nghiệp.", keywords: ["Tiến dần", "trưởng thành"] },
  { number: 54, symbol: "䷵", chinese: "歸妹", hanViet: "Lôi Trạch Quy Muội", code: "110100", upper: "Chấn", lower: "Đoài", theme: "Vai phụ · kết hợp chưa chuẩn", meaning: "Tượng kết hợp trong vị thế chưa cân hoặc quyết định bị cảm xúc đẩy nhanh.", whenCast: "Cần xem lại quyền hạn, cam kết và động cơ. Không thuận cho việc đặt mình vào thế phụ thuộc mà chưa rõ điều kiện.", keywords: ["Vai phụ", "kết hợp chưa chuẩn"] },
  { number: 55, symbol: "䷶", chinese: "豐", hanViet: "Lôi Hỏa Phong", code: "101100", upper: "Chấn", lower: "Ly", theme: "Phong thịnh · đỉnh sáng", meaning: "Sấm và lửa cùng mạnh: thời điểm nhiều việc, nhiều ánh sáng, nhiều thành quả.", whenCast: "Hãy tận dụng thời cực thịnh để làm việc lớn, nhưng đơn giản hóa và chuẩn bị cho lúc bớt sáng; không ai giữ đỉnh mãi.", keywords: ["Phong thịnh", "đỉnh sáng"] },
  { number: 56, symbol: "䷷", chinese: "旅", hanViet: "Hỏa Sơn Lữ", code: "001101", upper: "Ly", lower: "Cấn", theme: "Lữ hành · tạm trú", meaning: "Lửa trên núi không ở lâu: vị thế tạm thời, xa nhà hoặc chưa có gốc.", whenCast: "Hợp linh hoạt, giữ lễ và làm việc gọn. Đừng cư xử như chủ nhà khi mình đang ở vị trí tạm; giữ tài sản và quan hệ cẩn thận.", keywords: ["Lữ hành", "tạm trú"] },
  { number: 57, symbol: "䷸", chinese: "巽", hanViet: "Thuần Tốn", code: "011011", upper: "Tốn", lower: "Tốn", theme: "Thâm nhập · mềm bền", meaning: "Gió liên tục thấm vào: ảnh hưởng bằng sự mềm, lặp lại và kiên trì.", whenCast: "Không cần ép mạnh. Dùng thông tin, thói quen, thương lượng và từng bước nhỏ để thấm sâu; cần mục tiêu rõ để khỏi bị phân tán.", keywords: ["Thâm nhập", "mềm bền"] },
  { number: 58, symbol: "䷹", chinese: "兌", hanViet: "Thuần Đoài", code: "110110", upper: "Đoài", lower: "Đoài", theme: "Vui · giao tiếp", meaning: "Hồ nối hồ: niềm vui, trao đổi và thuyết phục qua lời nói.", whenCast: "Hợp đàm phán, chia sẻ và tạo không khí tích cực. Niềm vui phải chân thật; lời dễ nghe nhưng thiếu thực chất sẽ mất tín.", keywords: ["Vui", "giao tiếp"] },
  { number: 59, symbol: "䷺", chinese: "渙", hanViet: "Phong Thủy Hoán", code: "010011", upper: "Tốn", lower: "Khảm", theme: "Tan rã · giải tán bế tắc", meaning: "Gió trên nước làm tan khối cứng: giải phân cực, phá đóng băng.", whenCast: "Hợp gỡ chia rẽ, tái kết nối và giải tỏa tâm lý. Muốn tụ lại sau khi tan cần một trung tâm giá trị chung.", keywords: ["Tan rã", "giải tán bế tắc"] },
  { number: 60, symbol: "䷻", chinese: "節", hanViet: "Thủy Trạch Tiết", code: "110010", upper: "Khảm", lower: "Đoài", theme: "Tiết chế · giới hạn", meaning: "Nước trong hồ cần bờ: giới hạn giúp nguồn lực có hình và dùng được.", whenCast: "Nên đặt ngân sách, thời hạn, quy tắc và ranh giới. Kỷ luật có ích nhưng giới hạn quá khắc nghiệt sẽ phản tác dụng.", keywords: ["Tiết chế", "giới hạn"] },
  { number: 61, symbol: "䷼", chinese: "中孚", hanViet: "Phong Trạch Trung Phu", code: "110011", upper: "Tốn", lower: "Đoài", theme: "Trung tín · chân thành", meaning: "Chủ niềm tin phát từ bên trong, lời và lòng nhất quán.", whenCast: "Hợp thương lượng, cam kết và việc cần tín nhiệm. Sức thuyết phục đến từ chân thành và kiểm chứng được, không phải kỹ thuật nói suông.", keywords: ["Trung tín", "chân thành"] },
  { number: 62, symbol: "䷽", chinese: "小過", hanViet: "Lôi Sơn Tiểu Quá", code: "001100", upper: "Chấn", lower: "Cấn", theme: "Quá nhỏ · chú ý chi tiết", meaning: "Có thể vượt mức ở việc nhỏ nhưng không thuận cho đại sự.", whenCast: "Hợp sửa lỗi nhỏ, hạ thấp mục tiêu, cẩn thận chi tiết và giữ mình. Đừng biến một vấn đề nhỏ thành quyết định quá lớn.", keywords: ["Quá nhỏ", "chú ý chi tiết"] },
  { number: 63, symbol: "䷾", chinese: "既濟", hanViet: "Thủy Hỏa Ký Tế", code: "101010", upper: "Khảm", lower: "Ly", theme: "Đã hoàn thành · giữ thành", meaning: "Mọi hào đúng vị nhưng trạng thái hoàn thành rất dễ mất cân bằng.", whenCast: "Việc cơ bản đã xong. Trọng tâm chuyển sang kiểm tra, bảo trì và phòng lỗi nhỏ; chủ quan sau thành công là nguy cơ chính.", keywords: ["Đã hoàn thành", "giữ thành"] },
  { number: 64, symbol: "䷿", chinese: "未濟", hanViet: "Hỏa Thủy Vị Tế", code: "010101", upper: "Ly", lower: "Khảm", theme: "Chưa hoàn thành · chuyển tiếp", meaning: "Các yếu tố chưa vào đúng vị, nhưng chính vì chưa xong nên còn khả năng thay đổi.", whenCast: "Đang ở đoạn cuối nhưng chưa qua sông. Kiểm tra bước cuối, đừng vội mừng; giữ tỉnh táo để hoàn tất chuyển đổi.", keywords: ["Chưa hoàn thành", "chuyển tiếp"] },
];

const BY_NUMBER = new Map(ICHING_HEXAGRAMS.map((item) => [item.number, item]));
const BY_CODE = new Map(ICHING_HEXAGRAMS.map((item) => [item.code, item]));
export function getHexagramByNumber(number: number) { return BY_NUMBER.get(number) ?? null; }
export function getHexagramByCode(code: string) { return BY_CODE.get(code) ?? null; }

export type CoinLineValue = 6 | 7 | 8 | 9;
export type IChingCast = { lines: CoinLineValue[]; primary: IChingHexagram; changed: IChingHexagram | null; movingLines: number[]; };

export function buildIChingCast(lines: CoinLineValue[]): IChingCast {
  if (lines.length !== 6 || lines.some((value) => ![6,7,8,9].includes(value))) throw new Error("Cần đúng 6 hào có giá trị 6/7/8/9.");
  const primaryCode = lines.map((value) => value === 7 || value === 9 ? "1" : "0").join("");
  const changedCode = lines.map((value) => { const yang = value === 7 || value === 9; const moving = value === 6 || value === 9; return (moving ? !yang : yang) ? "1" : "0"; }).join("");
  const primary = getHexagramByCode(primaryCode);
  const changed = getHexagramByCode(changedCode);
  if (!primary || !changed) throw new Error("Không ánh xạ được mã quẻ.");
  const movingLines = lines.flatMap((value, index) => value === 6 || value === 9 ? [index + 1] : []);
  return { lines: [...lines], primary, changed: movingLines.length ? changed : null, movingLines };
}

export function castThreeCoins(random: () => number = Math.random): IChingCast {
  const lines: CoinLineValue[] = [];
  for (let line = 0; line < 6; line += 1) {
    let sum = 0;
    for (let coin = 0; coin < 3; coin += 1) sum += random() < 0.5 ? 2 : 3;
    lines.push(sum as CoinLineValue);
  }
  return buildIChingCast(lines);
}

export const MOVING_LINE_POSITION_NOTES = [
  "Hào 1 · sơ: việc mới manh nha; ưu tiên nền móng và tránh nóng vội.",
  "Hào 2: vị trí trung của nội quái; thường nhấn mạnh cách ứng xử thực tế và sự hỗ trợ gần.",
  "Hào 3: ranh cuối nội quái; dễ có căng thẳng khi chuyển từ ý định sang hành động.",
  "Hào 4: bước vào ngoại quái; chú ý quan hệ với môi trường, tổ chức hoặc người có quyền hơn.",
  "Hào 5: vị trí trung tâm của ngoại quái; thường là điểm chủ đạo/quyết định của tình thế.",
  "Hào 6 · thượng: sự việc đến cực điểm; cần nhìn dấu hiệu quá đà và chuẩn bị chuyển chu kỳ.",
] as const;
